### ISSUE TITLE
Current implementation is unsound. Segfault and double free are possible with out-of-sync maps from a bad `PartialEq` implementation.

### ISSUE THREAD

**Issue by steffahn** [jonhoo/evmap#1]
So basically, the current implementation seems to rely on the `PartialEq` implementation of a value for removing it. This is totally unsafe for the very same reasons why [retain](https://docs.rs/evmap/10/evmap/struct.WriteHandle.html#method.retain) is unsafe: You cannot guarantee that the `PartialEq` implementation gives the same result on two seperate calls with the same arguments.

```rust
use std::sync::atomic::{AtomicBool, Ordering::SeqCst};
static SNEAKY: AtomicBool = AtomicBool::new(false);

#[derive(Eq, Hash)]
struct Sneaky(Vec<u8>);
impl PartialEq for Sneaky {
    fn eq(&self, other: &Self) -> bool {
        if SNEAKY.swap(false, SeqCst) {
            false
        } else {
            self.0 == other.0
        }
    }
}

fn main() {
    let (_, mut w) = evmap::new::<u8, Box<Sneaky>>();
    w.insert(0, Box::new(Sneaky(vec![0])));
    w.refresh();
    w.remove(0, Box::new(Sneaky(vec![0])));
    SNEAKY.store(true, SeqCst);
    w.refresh();
    w.refresh();
    w.refresh();
}
```
```rust
$ cargo run
   Compiling evmaptest v0.1.0 (/home/frank/[...]/evmaptest)
    Finished dev [unoptimized + debuginfo] target(s) in 0.78s
     Running `target/debug/evmaptest`
[1]    30645 segmentation fault (core dumped)  cargo run
```

<hr>

Change to `struct Sneaky(u8);` and `Box::new(Sneaky(0))` and you get
```rust
free(): double free detected in tcache 2
[1]    31123 abort (core dumped)  cargo run
```
instead.

<hr>

Since Rust doesn’t have (and won’t have anytime soon) an effects system, we cannot guarantee “pure” implementations for e.g. `PartialEq` on the values type. I guess the only way to fix this is to make sure that the equality check happens only once, and then e.g. some kind of raw index into the bag is determined and stored into the op-log. That index only is then used for removing the same value from the other map.

I’m not familiar with the implementation details of this crate as to assess if this is possible and how hard of a change this would be but it seems like some nontrivial changes are needed. I’d suspect that `PartialEq` implementations (and perhaps also the `Hash` implementation?) of both the keys and the value type might be able to cause problems (I haven’t tested the behavior of the map for bad/sneaky key types yet though).

Also, @jonhoo I wanna say thanks for the great coding streams.

<hr>

A bit of testing shows that this exact code can produce a segfault on every version starting from version 5. I only tested the latest minor versions, i.e.: 5.1.1, 6.0.1, 7.1.3, 8.0.1, 9.0.1, 10.0.2, 11.0.0-alpha.1; as well as 5.0.0 and the current master and left-right branches.

<hr>

<details>
<summary>This code variation</summary>

```rust
use std::sync::atomic::{AtomicBool, Ordering::SeqCst};
static SNEAKY: AtomicBool = AtomicBool::new(false);

#[derive(Eq, Hash, Debug)]
struct Sneaky(Vec<u8>);
impl PartialEq for Sneaky {
    fn eq(&self, other: &Self) -> bool {
        if SNEAKY.swap(false, SeqCst) {
            false
        } else {
            self.0 == other.0
        }
    }
}

fn main() {
    let (r, mut w) = evmap::new::<u8, Box<Sneaky>>();
    let dbg = || r.get_and(&0, |vs| {
        println!("{:?}", vs);
    });
    w.insert(0, Box::new(Sneaky(vec![0])));
    w.refresh();
    w.remove(0, Box::new(Sneaky(vec![0])));
    SNEAKY.store(true, SeqCst);
    w.refresh();
    r.get_and(&0, |vs| {
        println!("{:?}", vs);
    });
    w.refresh();
    w.refresh();
    r.get_and(&0, |vs| {
        println!("{:?}", vs);
    });
}
```

</details>

leads to segfault on 2.0.0, 2.0.2, 3.0.1, 4.2.3. (and probably every other version 2-4 as well).

Version 1.* didn’t have `ShallowCopy` yet, so it probably should be fine.

**Comment by jonhoo** [comment]
Fixed in https://github.com/jonhoo/evmap/commit/849c661d3a3f0dca466dc657009b4901038508fc and released in `11.0.0-alpha.6` :tada:
