### ISSUE TITLE
Eventually consistent writes

### ISSUE THREAD

**Issue by Bajix** [jonhoo/evmap#11]
I wrote an eventually consistent [LRU](https://github.com/Bajix/evlru) earlier this week by leveraging crossbeam with evmap. This concept can be easily adapted for non-LRU use as to facilitate concurrent eventual writes with a version tailored for bounded use via crossbeam::queue:ArrayQueue and an unbounded version via crossbeam::queue::SegQueue. If you want this as part of evmap, you can run with the idea or I can push up a PR and we collaborate, otherwise I'll release this as a separate crate.

**Comment by jonhoo** [comment]
Hi there! I'd generally recommend keeping anything built on top of `left-right` as separate crates. If there's anything I've found with evmap, it's that concurrent datastructures tend to work best if they're tailored to a fairly specific use-case, and aiming for generality tends to sacrifice either performance or ergonomics. Nice that you found a good way to do it though, and thanks for checking!
